@ECHO OFF
REM BFCPEOPTIONSTART
REM Advanced BAT to EXE Converter www.BatToExeConverter.com
REM BFCPEEXE=
REM BFCPEICON=
REM BFCPEICONINDEX=-1
REM BFCPEEMBEDDISPLAY=0
REM BFCPEEMBEDDELETE=1
REM BFCPEADMINEXE=0
REM BFCPEINVISEXE=0
REM BFCPEVERINCLUDE=0
REM BFCPEVERVERSION=1.0.0
REM BFCPEVERPRODUCT=Symphony Electron
REM BFCPEVERDESC=Symphony desktop app (Foundation ODP)
REM BFCPEVERCOMPANY=Symphony
REM BFCPEVERCOPYRIGHT=© 2016 Symphony Software Foundation
REM BFCPEOPTIONEND
@ECHO ON
@echo off
start "" "%~dp0\Symphony-Electron.exe" --enable-sandbox
