name: Jest Coverage Report

on: [push, pull_request]

jobs:
  jest-coverage:

    runs-on: ubuntu-latest

    steps:
      - uses: ChristiaanScheermeijer/jest-reporter-action@v0.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-command: "npm run test:coverage"
