name: JIRA Description

on:
  pull_request_target:
    types: [opened, edited]

jobs:
  add-jira-description:
    runs-on: ubuntu-latest
    steps:
      - uses: alvisetrevisan/jira-details-action@master
        name: jira-description-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-base-url: https://perzoinc.atlassian.net
          skip-branches: '^(production-release|master|release\/v\d+)$'
