name: Review Reminder
on:
  schedule:
    - cron: '*/9 * * * *'

jobs:
  deploy:
    name: Review reminders
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: blombard/review-reminder@master
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        reminder-comment: "Don't forget to review this PR !"
        days-before-reminder: '1'
