name: Pull Request Stats

on:
  pull_request_target:
    types: [opened]

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repositories: 'symphonyoss/SymphonyElectron'
          period: 90
          charts: true
          sort-by: 'COMMENTS'
